"""Обновление значений KFALevel на коэффициенты активности

Revision ID: c3df19d7b6d0
Revises: 2025_01_20_1054
Create Date: 2026-02-01 10:25:43.817325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3df19d7b6d0"
down_revision: Union[str, None] = "2025_01_20_1054"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "privacy_consents",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=False),
        sa.Column(
            "consent_type",
            sa.Enum("PERSONAL_DATA", "COOKIES", "MARKETING", name="consenttype"),
            nullable=False,
        ),
        sa.Column("is_granted", sa.Boolean(), nullable=False),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.Column("policy_version", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_privacy_consents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_privacy_consents")),
    )
    op.create_index(
        "idx_privacy_consent_session_id",
        "privacy_consents",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "idx_privacy_consent_type",
        "privacy_consents",
        ["consent_type"],
        unique=False,
    )
    op.create_index(
        "idx_privacy_consent_user_id",
        "privacy_consents",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_privacy_consents_session_id"),
        "privacy_consents",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_privacy_consents_user_id"),
        "privacy_consents",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_privacy_consents_user_id"), table_name="privacy_consents")
    op.drop_index(op.f("ix_privacy_consents_session_id"), table_name="privacy_consents")
    op.drop_index("idx_privacy_consent_user_id", table_name="privacy_consents")
    op.drop_index("idx_privacy_consent_type", table_name="privacy_consents")
    op.drop_index("idx_privacy_consent_session_id", table_name="privacy_consents")
    op.drop_table("privacy_consents")
    # ### end Alembic commands ###
