version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgre
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/var/lib/postgresql/pg_hba.conf:ro
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf:ro
    command: -c config_file=/var/lib/postgresql/data/postgresql.conf
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    env_file:
      - .env
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}
    volumes:
      - ./config/postgres_exporter.yml:/postgres_exporter.yml
    command:
      - "--web.listen-address=:9187"
      - "--extend.query-path=/postgres_exporter.yml"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - LOG_LEVEL=${REDIS_LOG_LEVEL}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "127.0.0.1:${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping && rabbitmqctl status" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${APP_CONFIG__RUN__PORT}:${APP_CONFIG__RUN__PORT}"
    volumes:
      - ./src/app/core/certs:/nutricoreiq/src/app/core/certs
      - /home/deployer/nutricoreiq/src/app/logs:/nutricoreiq/src/app/logs
    container_name: web_app
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${APP_CONFIG__RUN__PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "production"
        env: "os,customer"

  taskiq_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskiq_worker
    command: >
      bash -c "sleep 30 && taskiq worker src.app.core.services.taskiq_broker:broker --workers 1 --fs-discover --tasks-pattern '**/tasks'"
    environment:
      - SENTRY_DSN=${APP_CONFIG__SENTRY__DSN}
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src/app/core/certs:/nutricoreiq/src/app/core/certs
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SERVER_PROTOCOL=${GF_SERVER_PROTOCOL}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fastapi
      - prometheus
      - grafana
      - loki
    networks:
      app-network:
        aliases:
          - nginx-app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./config/nginx/letsencrypt:/etc/letsencrypt
      - ./config/nginx/letsencrypt:/var/lib/letsencrypt
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    command: renew --quiet --deploy-hook "nginx -s reload"
    networks:
      - app-network
    depends_on:
      - nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "127.0.0.1:9100:9100"
    dns:
      - 127.0.0.11
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    depends_on:
      - nginx
    command: --nginx.scrape-uri=http://nginx-app:80/stub_status
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:latest
    container_name: loki
    labels:
      com.grafana.monitoring: "true"
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml -config.expand-env=true
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    labels:
      com.grafana.monitoring: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9080/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
  rabbitmq-data:
  loki_data:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
