auth_enabled: false

server:
  http_listen_port: 3100
  log_format: json  # Добавлено: Логи в JSON для лёгкого парсинга Promtail
  log_level: info   # Добавлено: Уровень логирования (можно изменить на debug для больше деталей)

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki

schema_config:
  configs:
    - from: 2020-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks

limits_config:
  retention_period: 168h  # Очистка раз в неделю

ingester:
  wal:
    enabled: true
    dir: /loki/wal

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  delete_request_store: filesystem
