services:
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_CONFIG__DB__USER} -d ${APP_CONFIG__DB__NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  maildev:
    image: maildev/maildev
    container_name: maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  test_db:
    image: postgres:17-alpine
    container_name: test_db
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__TEST_NAME}
      POSTGRES_USER: ${APP_CONFIG__DB__TEST_USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__TEST_PASSWORD}
    ports:
      - "5435:5432"

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    command: redis-server --save 60 1 --loglevel warning

volumes:
  pgdata:
  redisdata:
  rabbitmq-data:
